version: '3'
services:
    database:
        image: mongo
        container_name: database
        #ports:
        #- 37255:27017 # Keep commented out otherwise docker will expose this publically
        volumes:
          - /root/data:/data/db
        command: mongod
        restart: always
    
    bitcore-node:
        container_name: bitcore-node
        image: bitcorestrax.azurecr.io/bitcore-node
        depends_on:
        - database
        ports:
        - 3000:3000
        volumes:
        - /root/config:/config
        environment:
            - DB_HOST=database
            - DB_PORT=27017
            - BITCORE_CONFIG_PATH=/config/bitcore.config.testnet.json
        restart: always

    bws:
        container_name: bws
        image: bitcorestrax.azurecr.io/bws
        depends_on:
        - database
        - bitcore-node
        ports:
        - 80:3032
        volumes:
        - /root/config:/config
        environment:
            - DB_HOST=database
            - DB_PORT=27017
            - BWS_CONFIG_PATH=/config/bws.config.testnet.js
        restart: always